server:
  port: 443
  ssl:
    key-alias: howler-https
    key-store: hamza.jks
    key-store-type: JKS
    key-password: password
spring:
  datasource:
    url: jdbc:mysql://howlerdb.c3ko4k2m2jyu.ap-south-1.rds.amazonaws.com:3306/howlerdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
rzp_key_id: rzp_test_C6MyjQb5ed2Jvz
rzp_key_secret: 3kYCe8qIWA79puTHHcbqImLA
rzp_currency: INR
rzp_company_name: Howler