server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://howlerdb-1.ch2aw6om0j3d.ap-south-1.rds.amazonaws.com:3306/howlerDB
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
