server:
  port: 8443
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/howlerdb
    username: root
    password: Benten10@
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
rzp_key_id: rzp_test_C6MyjQb5ed2Jvz
rzp_key_secret: 3kYCe8qIWA79puTHHcbqImLA
rzp_currency: INR
rzp_company_name: Howler