server:
  port: 5454
spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:58169/railway
    username: root
    password: D6D1Fd3-2E5-3A23ggAeCDH2Ba1bbd56
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
rzp_key_id: rzp_test_C6MyjQb5ed2Jvz
rzp_key_secret: 3kYCe8qIWA79puTHHcbqImLA
rzp_currency: INR
rzp_company_name: Howler