server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/howlerdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
