name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout sourc
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t hamzashaikhcs/howler .
      - name: Publish image to docker hub
        run: docker push hamzashaikhcs/howler:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull hamzashaikhcs/howler:latest
      - name: Delete old container
        run: sudo docker rm -f howler-container
      - name: Run docker container
        run: sudo docker run -d -p 80:80 --name howler-container hamzashaikhcs/howler:latest
